from ..forms.form_loan import FormularioCrearPrestamos
from ..forms.form_income import FormularioCrearIngreso,FormularioActualizarIngreso
from ..forms.form_account import FormularioCrearCuenta,FormularioActualizarCuenta
from ..forms.form_loanpayments import FormularioCrearPagoPrestamo
from ..forms.form_scheduled_incomes import FormularioCrearIngresoProgamado,FormularioActualizarIngresoProgramado
from ..forms.form_service import FormularioCrearServicio
from ..forms.form_servicepayments import FormularioCrearPagoServicio
from ..forms.form_user import FormularioRegistro,FormularioInicio
FormularioActualizarIngreso
FormularioActualizarCuenta
FormularioCrearPrestamos
FormularioCrearIngreso
FormularioCrearCuenta
FormularioCrearPagoPrestamo
FormularioCrearIngresoProgamado
FormularioCrearServicio
FormularioCrearPagoServicio
FormularioActualizarIngresoProgramado
FormularioRegistro
FormularioInicio